title: Worst Practice
lang: en
locale: en_US
author: 'Gábor Iván'
author_slug: 'gabor.ivan'
author_avatar: '/assets/img/gabor.ivan.jpg'
application: 'Worst Practice Blog'

author_introduction: ''
description: ''
subject: ''
copyright: 'Copyright © 2019-2020, Gixx-web (https://www.gixx-web.com). All rights reserved.'
keywords: ''

homepage: 'https://www.worstpractice.dev'

default_categories: ['Home']
default_tags: ['']
default_rating: false

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
      page_categories: ['Home']
      page_tags: ['']
      page_type: 'post_list'
  -
    scope:
      path: ''
      type: 'posts'
    values:
      layout: 'post'
      page_type: 'post_view'

destination: docs

facebook_appid: 2178081495757871
facebook_username: ivan.gabor.80
twitter_username: gaborivan1980
github_username: Gixx
linkedin_username: gaborivan

future: true

exclude:
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .jekyll-cache

env: production

excerpt_separator: <!--more-->

reversed_categories:
  - tutorial

markdown: CommonMark

commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table"]

permalink: /:categories/:title.html

autopages:
  enabled: true
  tags:
    layouts:
      - taglist.html
    title: ''
    permalink: /tags/:tag/
    enabled: true
  categories:
    layouts:
      - categorylist.html
    title: ''
    permalink: /:cat/
    enabled: true
  collections:
    enabled: false

jekyll-archives:
  enabled:
    - month
  layouts:
    month: 'datelist'
  permalinks:
    month: '/archive/:year-:month/'

pagination:
  enabled: true
  per_page: 10
  offset: 0
  permalink: '/page/:num.html'
  title: ':title - Page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

plugins:
  - jekyll-feed
  - jekyll-commonmark
  - jekyll-archives
  - jekyll-include-cache
  - rouge
  - jekyll-last-modified-at
  - jekyll-plantuml
  - jekyll-tidy
  - classifier-reborn
  - jekyll-tagging-related_posts
  - jekyll-paginate-v2

jekyll_tidy:
  exclude: ['robots.txt']
  compress_html: false

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  input: GFM
  syntax_highlighter: rouge
