version: '3.7'
services:

  jekyll:
    container_name: 'jekyll-wp'
    image: 'jekyll/jekyll:3.8'
    ports:
      - '4000:4000'
    volumes:
      - './:/srv/jekyll'
    command: tail -f /dev/null

  webpack:
    container_name: 'webpack-wp'
    image: 'node:13'
    volumes:
      - './:/app'
    command: tail -f /dev/null
